// <auto-generated />
using Day09Lab_231230949_17_10_2025.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day09Lab_231230949_17_10_2025.Migrations
{
    [DbContext(typeof(HvtDay09LabCFContext))]
    partial class HvtDay09LabCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day09Lab_231230949_17_10_2025.Models.HvtLoai_San_Pham", b =>
                {
                    b.Property<long>("hvtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("hvtId"));

                    b.Property<string>("hvtMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hvtTenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("hvtTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("hvtId");

                    b.HasIndex("hvtMaLoai")
                        .IsUnique();

                    b.ToTable("HvtLoai_San_Pham");
                });

            modelBuilder.Entity("Day09Lab_231230949_17_10_2025.Models.HvtSan_Pham", b =>
                {
                    b.Property<long>("hvtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("hvtId"));

                    b.Property<decimal>("hvtDonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("hvtHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("hvtLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<long>("hvtLoai_San_PhamhvtId")
                        .HasColumnType("bigint");

                    b.Property<string>("hvtMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("hvtSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("hvtTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hvtId");

                    b.HasIndex("hvtLoai_San_PhamhvtId");

                    b.ToTable("HvtSan_Pham");
                });

            modelBuilder.Entity("Day09Lab_231230949_17_10_2025.Models.HvtSan_Pham", b =>
                {
                    b.HasOne("Day09Lab_231230949_17_10_2025.Models.HvtLoai_San_Pham", "hvtLoai_San_Pham")
                        .WithMany("hvtSan_Phams")
                        .HasForeignKey("hvtLoai_San_PhamhvtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hvtLoai_San_Pham");
                });

            modelBuilder.Entity("Day09Lab_231230949_17_10_2025.Models.HvtLoai_San_Pham", b =>
                {
                    b.Navigation("hvtSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
